package main

import (
	"context"
	"flag"
	"fmt"
	"io"
	"log"
	"os"
	"strings"
)

const VERSION string = "1.0.0"

// alias for model
type Model string

const (
	free  Model = "gemma-4-26b-a4b-it"
	cheap Model = "gemini-3.1-flash-lite-preview"
	exp   Model = "gemini-3-flash-preview"
)

// alias for reasoning level
type Thought string

const (
	HIGH Thought = "HIGH"
	MED  Thought = "MEDIUM"
	LOW  Thought = "LOW"
	MIN  Thought = "MINIMAL"
)

func resolveModels(m string) string {
	switch m {
	case "free":
		return string(free)
	case "cheap":
		return string(cheap)
	case "exp":
		return string(exp)
	default:
		return m
	}
}

func resolveReasoningLevel(t string) string {
	switch t {
	case "HIGH":
		return string(HIGH)
	case "MED":
		return string(MED)
	case "LOW":
		return string(LOW)
	case "MIN":
		return string(MIN)
	default:
		return t
	}
}

var help = flag.Bool("help", false, "Show help menu")
var model = flag.String(
	"model",
	string(free),
	"the model name, e.g. gemma-4-26b-a4b-it")
var version = flag.Bool(
	"version",
	false,
	"the current version of the package",
)
var reasoning = flag.String(
	"reason",
	string(MIN),
	"reasoning effort, e.g. HIGH, MED, LOW, MIN",
)
var clr = flag.Bool(
	"clear",
	false,
	"clear the local database. WARNING: This will remove all the past conversations",
)

func checkForEnv() (string, bool) {
	value, exists := os.LookupEnv("GEMINI_API_KEY")
	if !exists {
		log.Fatal("GEMINI API KEY not found in the PATH. Add the key to the path and restart the program")
	}
	return value, true
}

func main() {
	var stdinInput string
	stat, _ := os.Stdin.Stat()
	if (stat.Mode() & os.ModeCharDevice) == 0 {
		bytes, err := io.ReadAll(os.Stdin)
		if err != nil {
			log.Fatal(err)
		}
		stdinInput = string(bytes)
	}

	flag.Parse()
	ctx := context.Background()

	db := initDB()
	defer db.Close()

	if *help {
		helpMenu()
		os.Exit(0)
	}

	if *version {
		fmt.Println("ask\nversion: ", VERSION)
		os.Exit(0)
	}

	if *clr {
		clearDatabase(db)
		fmt.Println("Removed all the rows from the database. Start afresh!")
		os.Exit(0)
	}

	e, _ := checkForEnv()
	args := flag.Args()
	if len(args) == 0 {
		helpMenu()
		os.Exit(1)
	}
	query := strings.Join(args, " ")

	if stdinInput != "" && query != "" {
		query = query + "\n\n" + stdinInput
	} else if stdinInput != "" {
		query = stdinInput
	}
	if query == "" {
		helpMenu()
		os.Exit(1)
	}

	// saving user message (final query includes piped stdin when present)
	saveMessage(db, "user", query)

	fmt.Print("thinking...")
	res := run(ctx, e, query, resolveModels(*model), resolveReasoningLevel(*reasoning))
	fmt.Print("\r				\r")

	// saving responses generated by the assistant
	saveMessage(db, "assistant", res)
	render("# Final Response\n" + res)
}
